name: Java CI

on: [push]

jobs:
  CI:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Install leiningen
        run: brew install leiningen
        
      - name: Build libs
        run: make libs
        
      - name: Test
        run: make test
                
      - name: Build package
        run: make clean all
        
      - name: list build directory
        run: |
          ls -ltr build/
      
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        if: always()
        with:
          name: infra-problem-jars
          path: ./build
          retention: 10
          
      - name: Get gh run ID to download artifacts
        run: echo "$GITHUB_RUN_ID"
        
